import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { DEFAULT_CONFIG, type WikipilotConfig } from "./config.js";

const REPO_URL = "https://github.com/guymoyal/wikipilot";

/** Section-specific authoring guidance, so a page lands with the right shape for its audience. */
const SECTION_BRIEFS: Record<string, string> = {
  "start-here": "What this is and who it's for, in the first two sentences. Orientation only — link out rather than explaining everything here.",
  "getting-started": "Install steps and the shortest path to a first real result. Every command copy-pasteable and actually run before you write it down.",
  guides: "One page per task a reader wants to accomplish, named after the goal (\"Import an existing project\") not the module (\"The import service\"). Numbered steps, with the expected output shown.",
  "how-it-works": "The real control/data flow through the system. This is where sequence and architecture diagrams belong, and where a wrong diagram does the most damage — trace it in the code first.",
  technologies: "Why this dependency is here and what it's used for in *this* repo, not what its own docs say. Link to the files that use it.",
  cookbook: "Short recipes: the task, the command, the result. Assume the reader has already read Getting Started.",
  faq: "Real questions in the words people actually use, each answered in the first two sentences before any elaboration.",
  troubleshooting: "Symptom → cause → fix. Add an entry every time a problem costs someone more than a minute.",
  reference: "Exhaustive lookup material — flags, config keys, schemas, endpoints. Generated from the source of truth wherever possible.",
};

function sectionGuidance(sections: string[]): string {
  return sections
    .filter((section) => SECTION_BRIEFS[section])
    .map((section) => `- \`${section}/\` — ${SECTION_BRIEFS[section]}`)
    .join("\n");
}

export function scaffoldUpdateWikiSkill(
  targetDir: string,
  wikiDir: string,
  config: WikipilotConfig = DEFAULT_CONFIG,
): string {
  const skillDir = join(targetDir, ".claude", "skills", "update-wiki");
  mkdirSync(skillDir, { recursive: true });
  const relWikiDir = relative(targetDir, wikiDir) || "wiki";

  const content = `---
name: update-wiki
description: Write and maintain this repo's wikipilot wiki (${relWikiDir}/) so pages stay true to the current code. Use when asked to "update the wiki", "sync the wiki", "audit the wiki", or to write/expand a wiki page.
---

This repo's wiki lives at \`${relWikiDir}/content/<locale>/<section>/<slug>.md\`, generated by [wikipilot](${REPO_URL}) and built with \`wikipilot build\`. This wiki uses the **${config.preset}** preset — its sections are \`${config.sections.join("`, `")}\`.

Every page declares a freshness contract in its frontmatter:

\`\`\`yaml
---
title: The Publish Pipeline
description: How a draft becomes a published document.
section: how-it-works
order: 2                 # optional; controls sidebar position
sources:                 # repo globs this page documents
  - packages/publish-service/**
last_synced: "d70bf9ba"  # commit SHA when prose was last verified against sources
version: "1.4.0"         # the project's package.json version at that moment
stale: false             # true when sources changed and prose wasn't confidently patched
---
\`\`\`

\`last_synced\` and \`version\` answer different questions. The SHA is what you diff against; the version is what a reader recognises ("this documents 1.4, we're on 2.0"). Whenever you re-stamp one, re-stamp the other.

\`sources\` is the contract. A page with vague sources (\`**/*\`) can never be checked for drift, and a page with no sources is invisible to every mode below. Always set the narrowest globs that actually cover the page.

---

## Mode 1 — Author ("write the wiki page for X", "document Y")

Read the code before you write the page. Not the filenames — the code.

1. **Find the real sources.** Locate the files that implement the thing. These become \`sources\`, as narrow as you can make them.
2. **Read them fully**, plus their tests — tests state intended behaviour more honestly than comments do.
3. **Pick the section** from the list below and write to its brief:

${sectionGuidance(config.sections)}

4. **Write the page.** Lead with what the thing does and why it exists, before how it works. Concrete names, real paths, real commands.
5. **Stamp it**: \`last_synced\` = \`git rev-parse --short HEAD\`, \`version\` = the project's current \`package.json\` version, \`stale: false\`, and a one-line \`description\` (it's the search/preview text and the sidebar blurb).
6. **Verify** with \`wikipilot build ${relWikiDir}\` before finishing.

### Code examples — pull them, don't write them

Every snippet must be **copied from a real file**, not composed from memory. Caption it with the path it came from:

\`\`\`\`
\`\`\`ts title="src/billing/refunds.ts"
export async function issueRefund(chargeId: string) {
  // …the actual lines from the file
}
\`\`\`
\`\`\`\`

The \`title="…"\` renders as a caption above the block. It is also how the next person (or the next sync run) knows which file to re-read to check the snippet. A snippet without a path is unverifiable — always add one.

Trim to the lines that matter and mark elisions with \`// …\`, but never edit the lines you keep. If a snippet needs changing to be correct, the *code* changed — go re-read it.

### Diagrams — mermaid, and only where it earns its place

Mermaid renders natively in the built wiki. Use it when structure is genuinely hard to hold in prose, not as decoration:

- **\`flowchart\`** — how components/services connect, request paths, decision logic.
- **\`sequenceDiagram\`** — multi-actor flows over time: auth handshakes, retries, queue → worker → callback.
- **\`erDiagram\`** — data models and relationships, drawn from the real schema/migrations.
- **\`stateDiagram-v2\`** — lifecycles with defined states: order status, job state, subscription.
- **\`classDiagram\`** — only when the type relationships are the point.

\`\`\`\`
\`\`\`mermaid
sequenceDiagram
    participant C as Client
    participant A as API
    participant Q as Queue
    C->>A: POST /publish
    A->>Q: enqueue(job)
    A-->>C: 202 Accepted
    Q->>A: job complete
\`\`\`
\`\`\`\`

Rules for diagrams:
- **Derive every node and edge from code you have read.** An invented arrow is a lie with a diagram's authority — worse than no diagram.
- Keep it under ~12 nodes. Split into two diagrams before letting one become unreadable.
- Label edges with what actually crosses them (\`POST /publish\`, \`job_id\`), not \`calls\`.
- Name nodes after the real modules/services in this repo.
- Add a sentence before each diagram saying what to look at in it.

### Formatting constraints

The renderer is markdown-it with **raw HTML disabled** and no syntax-highlighting pass. So:
- Raw \`<div>\`/\`<img>\`/\`<br>\` tags will not render — use markdown, or mermaid for visuals.
- Tables, task lists, and fenced code all work. Language tags are for labelling, not colouring.
- Links between pages are relative to the built URL, and every page is served at \`/<section>/<slug>/\` — so linking across sections goes up two levels: \`[Refunds](../../guides/refunds/)\`. Within the same section it's one: \`[Refunds](../refunds/)\`.

---

## Mode 2 — Sync ("update the wiki" / "sync the wiki")

1. For each page under \`${relWikiDir}/content/\`, read its \`sources\` and \`last_synced\`, then run:
   \`git diff --name-only <last_synced>..HEAD -- <sources>\`
   Pages with no matching diff are unchanged — skip them and leave their SHA alone (an old SHA is honest information, not a bug).
2. For each page with real diffs: read the actual changed source files (never guess or "clean up" prose without reading the code). Either:
   - **Confidently patch** the prose, snippets, and diagrams to match reality, then bump \`last_synced\` to \`git rev-parse --short HEAD\`, set \`version\` to the current \`package.json\` version, and clear \`stale\`.
   - If you can't confidently patch it, set \`stale: true\` and leave a one-line note in the page body about what changed, so a human sees a visible "may be outdated" banner instead of silently-wrong docs.
3. Re-read every snippet's \`title="<path>"\` file and every diagram's underlying code — those drift the fastest and are the most confidently wrong when they do.
4. If \`wikipilot.config.json\` declares \`sourcesOfTruth\` (e.g. a service registry file), check whether new entities there (services, agents, tables) have no covering page yet. If so, author a page for each via Mode 1.
5. If this repo has more than one locale configured (\`wikipilot.config.json\` → \`locales\`), and a page you just patched has a translated mirror at \`content/<other-locale>/<section>/<slug>.md\`, re-translate the affected parts of that mirror too (prose only — code, paths, and commands stay verbatim).
6. If the project's \`package.json\` version has moved on, update \`version\` in \`${relWikiDir}/wikipilot.config.json\` too — that's what the wiki header displays.
7. Run \`wikipilot build ${relWikiDir}\` as a correctness check before finishing.
8. Land the result as a small, reviewable commit/PR (don't push automatically) — a human should eyeball AI-updated docs before they merge.

---

## Mode 3 — Audit ("audit the wiki")

Do everything in sync mode, plus:
- Check **every** page regardless of whether its sources changed, to catch pages whose \`sources\` glob itself is stale (points at deleted or renamed files).
- Flag pages whose \`sources\` are too broad to be meaningful (\`**/*\`, a whole top-level directory) — they silently never report drift.
- Grep the repo for services, agents, tables, routes, and technologies that no page's \`sources\` cover at all. These are documentation gaps, not staleness. List them for a human to decide.
- Check the wiki against its preset: a **${config.preset}** wiki should have real content in \`${config.sections.join("`, `")}\`. Report sections that are still just the scaffolded placeholder.

---

## Ground rules

- Never hand-edit a code snippet "to look right" — always re-read the live file at the path in the snippet's \`title="<path>"\` (or in \`sources\`) before touching it.
- Don't invent facts to fill gaps. A stale or incomplete page beats a confidently wrong one.
- Don't document intent you can't find in the code. If you need to state a "why" you can't verify, mark it as an open question for a human.
- Keep the diff small and reviewable — this is prose maintenance, not a rewrite.
`;

  writeFileSync(join(skillDir, "SKILL.md"), content, "utf8");
  return join(skillDir, "SKILL.md");
}
